### ISSUE TITLE
The error comes when you turn

### ISSUE THREAD

**Issue by Sina30** [CriMsOnN/rm_queue#1]
The error comes when you turn it on and everything is running correctly, then restart the server again

[     script:rm_queue] true
[     script:rm_queue] SCRIPT ERROR in promise (unhandled rejection): Error: No such export playerConnecting in resource vorp_core
[     script:rm_queue] > eval (webpack://rm_queue/./server/server.ts?:114)
[     script:rm_queue] > Generator.next (<anonymous>:0)
[     script:rm_queue] > fulfilled (webpack://rm_queue/./server/server.ts?:5)
[     script:rm_queue] > process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:61)
[     script:rm_queue]

**Comment by CriMsOnN** [comment]
Edit config.json and set useExternal to false or download the updated one i just pushed a commit to change useExternal to false by default.
